name: "新内容提案"
description: "对已有内容的大幅度更改，或添加一个新内容。"
title: "[新内容] "
labels: [· 新内容, 新反馈]
body:
- type: checkboxes
  id: "yml-1"
  attributes:
    label: "检查项"
    description: "请检查下列项目，并勾选确认。"
    options:
    - label: "我已在 [Issues 页面](https://fasthub.cc/StarPixel-Team/PCL-Client/issues?q=is%3Aissue+) 中搜索，确认了这一反馈未被提交过。"
    - label: "我已在启动页面右侧点击“检查更新”，确认客户端为最新版，且最新版未添加该内容。"
      required: true
- type: textarea
  id: "yml-2"
  attributes:
    label: "描述"
    description: "详细描述需要添加的新内容。"
    value: |
      （示例）
      添加新的帮助文档：如何在 GitHub 提交反馈。
  validations:
    required: true
- type: textarea
  id: "yml-3"
  attributes:
    label: "原因"
    description: "描述为何需要该内容。"
    value: |
      （示例）
      很多人都不知道如何使用 GitHub，因此需要添加此内容，以保证所有人都能够提交反馈。
  validations:
    required: true
