name: "优化建议"
description: "对已有内容的小幅度更改。"
title: "[优化] "
labels: [· 优化, 新反馈]
body:
- type: checkboxes
  id: "yml-1"
  attributes:
    label: "检查项"
    description: "请检查下列项目，并勾选确认。"
    options:
    - label: "我已在 [Issues 页面](https://github.com/StarPixel-Team/PCL-Client/issues?q=is%3Aissue+) 中搜索，确认了这一反馈未被提交过。"
    - label: "我已在启动页面右侧点击“检查更新”，确认客户端为最新版，且最新版未添加该内容。"
      required: true
- type: textarea
  id: "yml-2"
  attributes:
    label: "描述"
    description: "详细描述需要修改的地方。"
    value: |
      （示例）
      在更新客户端时，不下载其中的全部文件，仅下载更改的文件。
  validations:
    required: true
- type: textarea
  id: "yml-3"
  attributes:
    label: "原因"
    description: "描述为何需要修改。"
    value: |
      （示例）
      这样能够避免重复文件的下载，能够提高更新速度。
  validations:
    required: true
